.TH xpmtoppm 1 "16 August 1990"
.SH NAME
xpmtoppm - convert an X11 pixmap into a portable pixmap
.SH SYNOPSIS
.B xpmtoppm
.RI [ xpmfile ]
.SH DESCRIPTION
Reads an X11 pixmap (XPM version 1 or 3) as input.
Produces a portable pixmap as output.
.SH KNOWN BUGS
The support to XPM version 3 is limited. Comments can only be single lines
and there must be for every pixel a default colorname for a color type visual.
.SH "SEE ALSO"
ppmtoxpm(1), ppm(5)
.br
XPM Manual by Arnaud Le Hors lehors@mirsa.inria.fr
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.

Upgraded to support XPM version 3 by
    Arnaud Le Hors (lehors@mirsa.inria.fr)
    Tue Apr 9 1991
