/*
 * keyword.h -- Keyword manifest constants.
 *
 * Created mechanically by mkkwd.icn -- DO NOT EDIT.
 */

#define K_ALLOCATED    1
#define K_ASCII        2
#define K_CLOCK        3
#define K_COL          4
#define K_COLLECTIONS  5
#define K_COLUMN       6
#define K_CONTROL      7
#define K_CSET         8
#define K_CURRENT      9
#define K_DATE        10
#define K_DATELINE    11
#define K_DIGITS      12
#define K_DUMP        13
#define K_E           14
#define K_ERROR       15
#define K_ERRORNUMBER 16
#define K_ERRORTEXT   17
#define K_ERRORVALUE  18
#define K_ERROUT      19
#define K_EVENTCODE   20
#define K_EVENTSOURCE 21
#define K_EVENTVALUE  22
#define K_FAIL        23
#define K_FEATURES    24
#define K_FILE        25
#define K_HOST        26
#define K_INPUT       27
#define K_INTERVAL    28
#define K_LCASE       29
#define K_LDRAG       30
#define K_LETTERS     31
#define K_LEVEL       32
#define K_LINE        33
#define K_LPRESS      34
#define K_LRELEASE    35
#define K_MAIN        36
#define K_MDRAG       37
#define K_META        38
#define K_MPRESS      39
#define K_MRELEASE    40
#define K_NULL        41
#define K_OUTPUT      42
#define K_PHI         43
#define K_PI          44
#define K_POS         45
#define K_PROGNAME    46
#define K_RANDOM      47
#define K_RDRAG       48
#define K_REGIONS     49
#define K_RESIZE      50
#define K_ROW         51
#define K_RPRESS      52
#define K_RRELEASE    53
#define K_SHIFT       54
#define K_SOURCE      55
#define K_STORAGE     56
#define K_SUBJECT     57
#define K_TIME        58
#define K_TRACE       59
#define K_UCASE       60
#define K_VERSION     61
#define K_WINDOW      62
#define K_X           63
#define K_Y           64
