Build:
	icont -s -c -u draw_crc
	icont -s -c -u data
	icont -s -c -u draw_sqr
	icont -s -c -u draw_rec
	icont -s -c -u draw_box
	icont -s -c -u draw_bar
	icont -s -c -u clr_list
	icont -s -u drawtree

Clean:
	rm -f *.u* drawtree
