# top-level Icon makefile, configured for Windows NT
Top:
	@echo Run "nmake Configure" or "nmake W-Configure" to configure sources

Configure:
	cd \v9\config\nt\msvc
	config
	echo Run "nmake Icon-icont" to build

W-Configure:
	cd \v9\config\nt\msvc
	w-config
	echo Run "nmake Icon-icont" to build

Icon-icont:
        nmake Rtt
        cd \v9\src\runtime
	nmake interp_all
        cd \v9\src\icont
	nmake

Rtt:
        cd src\rtt
	nmake
