SHELL=/bin/sh
MAKE=make

what:
	@echo "What do you want to make?"

Clean:
		rm -f *.o

# Entries beyond this point are for use at Arizona only.
#   *** Do not delete the line above; it is used in trimming Makefiles
#   for distribution ***

Dist-clean:
		rm -rf `gcomp README Makefile *.r *.icn`
