#  note that only carport is built here
#  carplay is built by the carport program after generating carpincl.icn

carport:
		icont -usc carputil carprec
		icont -us carport


#  build executable and copy to ../../iexe
#  (nothing done in this case because the executable doesn't stand alone)
Iexe:		

Clean:
		rm -f carport carplay carpincl.icn *.u[12]
