#  note that only carport is built here
#  carplay is built by the carport program after generating carpincl.icn

carport:
		icont -usc carputil carprec
		icont -us carport

Clean:
		rm -f carport carplay carpincl.icn *.u[12]
