.TH ICON 1 "15 January 2002" "University of Arizona"
.SH NAME
icon \- execute Icon program
.SH SYNOPSIS
\fBicon\fP sourcefile [ arg ... ]
.br
\fBicon \-P\fP 'program' [ arg ... ]
.SH DESCRIPTION
.I Icon
is a simple interface for executing programs written
in the Icon programming language.
The source code is translated and linked,
then executed with the given list of arguments.
.PP
Without
.BR \-P ,
a single source file is read;
its name need not necessarily end in
.BR .icn .
With
.BR \-P ,
a small program can be embedded within a larger shell script.
.PP
An Icon source file can be made directly executable
by setting the appropriate permission bits and
beginning it with a shell header.
If the first line of the file is
.in +.5i
.B #!/usr/bin/env icon
.in
then
.I icon
is found on the command search path
and called to process the program upon execution.
.SH ENVIRONMENT
The environment variables described under
.IR icont (1)
can also be used with the
.I icon
command.
Normally, none of these are needed.
.SH SEE ALSO
.IR icont (1),
the full-featured interface supporting separate compilation,
multiple source files, and other features.
.LP
.IR "The Icon Programming Language" .
Griswold and Griswold,
Peer-to-Peer, third edition, 1996.
.LP
.IR "Graphics Programming in Icon" .
Griswold, Jeffery, and Townsend,
Peer-to-Peer, 1998.
.LP
.IR "Version 9.4 of Icon" .
http://www.cs.arizona.edu/icon/v940.
