#!/bin/sh
#
#  <ARIZONA-ONLY> <#%#%#%#%# TEMPORARY #%#%#%#%>

for d in *_*; do
   echo $d 1>&2
   cd $d
   (
   echo "#  Makefile definitions from config/unix/$d"
   cat <<'==EOF=='

#  CC       C compiler
#  CFLAGS   flags for building C files
#  RLINK    flags for linking run-time system
#  RLIBS    libraries to link with run-time system
#  XINCL    include path for graphics
#  XLINK    linking arguments for graphics
#  XPMDEFS  definitions for building XPM library

==EOF==
   grep CC= runtime.hdr
   grep CFLAGS rtt.hdr
   grep LDFLAGS runtime.hdr | sed s/LDFLAGS/RLINK/
   grep LIBS runtime.hdr | sed s/LIBS/RLIBS/
   grep XINCL runtime.hdr
   grep XLIB xiconx.mak | sed s/XLIB/XLINK/
   grep XPMDEFS xpm.hdr
   ) | sed >Makedefs '
	s/+=/=/
	s/ *= */ = /
   ' >Makedefs
   cd ..
done
