SHELL=/bin/sh
MAKE=make

all:

##################################################################
# Entries beyond this point are for use at Arizona only.
#   *** Do not delete the line above; it is used in trimming Makefiles
#   for distribution ***

Dist-clean:
	rm -rm Ppdef
